# Copyright 2022 Tuan Anh Tran <me@tuananh.org>

name: gen-trivy-badge
description: |
  This action generate Trivy scan result badge.
inputs:
  image:
    description: |
      image used for scanning
    required: true
  badge-style:
    description: |
      badge style (flat, flat-square, plastic, social)
    default: flat-square

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        wget https://raw.githubusercontent.com/tuananh/actions/main/gen-trivy-badge/template.txt
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ inputs.image }}
        format: 'template'
        template: '@template.txt'
        output: 'trivy_scan_result.yaml'
    - name: Debug
      shell: bash
      run: |
        sed -i $'s/,/\\\n/g' trivy_scan_result.yaml
        cat trivy_scan_result.yaml

        output=""
        output+="![critical cve](https://img.shields.io/static/v1?label=critical&message=$(yq -r '.critical_cve_count' trivy_scan_result.yaml)%20&style=${{inputs.badge-style}}&color=red)"
        output+=" ![high cve](https://img.shields.io/static/v1?label=high&message=$(yq -r '.high_cve_count' trivy_scan_result.yaml)%20&style=${{inputs.badge-style}}&color=orange)"
        output+=" ![medium cve](https://img.shields.io/static/v1?label=medium&message=$(yq -r '.medium_cve_count' trivy_scan_result.yaml)%20&style=${{inputs.badge-style}}&color=yellow)"
        output+=" ![low cve](https://img.shields.io/static/v1?label=low&message=$(yq -r '.low_cve_count' trivy_scan_result.yaml)%20&style=${{inputs.badge-style}}&color=yellowgreen)"

        echo $output

        sed -i '/<!-- TRIVY_BADGE_START -->/,/<!-- TRIVY_BADGE_END -->/c<!-- TRIVY_BADGE_START -->\n'"$output"'\n<!-- TRIVY_BADGE_END -->' README.md