# Copyright 2022 Tuan Anh Tran <me@tuananh.org>

name: gen-key
description: |
  This action generate Trivy scan result badge.
inputs:
  image:
    description: |
      image used for scanning
    required: true

runs:
  using: "composite"
  steps:
    - id: trivy-template
      shell: bash
      run: |
        wget https://raw.githubusercontent.com/tuananh/actions/main/gen-trivy-badge/template.txt
        TRIVY_TEMPLATE=$(cat template.txt)
        echo "TRIVY_TEMPLATE<<EOF" >> $GITHUB_ENV
        echo "$TRIVY_TEMPLATE" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
    - shell: bash
      run: |
        echo ${{ env.TRIVY_TEMPLATE }}
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ inputs.image }}
        format: 'template'
        template: ${{ steps.trivy-template.outputs.template }}
        output: 'trivy_scan_result.yaml'
    - name: Debug
      shell: bash
      run: |
        cat trivy_scan_result.yaml