# Copyright 2022 Tuan Anh Tran <me@tuananh.org>

name: gen-key
description: |
  This action generate Trivy scan result badge.
inputs:
  image:
    description: |
      image used for scanning
    required: true

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        wget https://raw.githubusercontent.com/tuananh/actions/main/gen-trivy-badge/template.txt
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ inputs.image }}
        format: 'template'
        template: '@template.txt'
        output: 'trivy_scan_result.yaml'
    - name: Debug
      shell: bash
      run: |
        sed -i $'s/,/\\\n/g' trivy_scan_result.yaml
        cat trivy_scan_result.yaml