# Copyright 2022 Tuan Anh Tran <me@tuananh.org>

name: Setup crane
description: |
  This action sets up crane - https://github.com/google/go-containerregistry/blob/main/cmd/crane/README.md

inputs:
  ref:
    description: The GitHub ref to install. Defaults to latest.
    required: false
    default: "latest"
  update-path:
    description: Add GOPATH/bin to PATH variable
    required: false
    default: "true"

runs:
  using: "composite"

  steps:
    - name: Install crane
      shell: bash
      run: |
        go install github.com/google/go-containerregistry/cmd/crane@${{ inputs.ref }}
    - name: Update $PATH
      shell: bash
      run: export PATH=${PATH}:`go env GOPATH`/bin
      if: ${{ github.event.inputs.update-path == 'true' }}
