# Copyright 2022 Tuan Anh Tran <me@tuananh.org>

name: gen-key
description: |
  This action generate SSH key.
inputs:
  email:
    description: |
      email used for creating the key
    required: true

  signing-key-path:
    description: |
      The path to put the signing key at.
    default: ${{ github.workspace }}/id_rsa
    required: false

  install-public-key:
    description: |
      Whether to add the generated key to the system APK keyring.
    default: "true"
    required: false
  
  output-name:
    description: |
      Output name to be used in other steps.
    default: ssh_pub_key
    required: false

runs:
  using: "composite"
  steps:
    - name: Generate ssh key pair
      shell: bash
      run: |
        ssh-keygen -t rsa -b 4096 -C "${{ inputs.email }}" -f ${{ inputs.signing-key-path }} -q -N ""
        cat "${{ inputs.signing-key-path }}.pub"
        echo "::set-output name=${{ inputs.output-name }}::$(cat ${{ inputs.signing-key-path }}.pub)"

    # - name: 'Install public key in system keyring'
    #   shell: bash
    #   run: |
    #     sudo cp ${{ inputs.signing-key-path }}.pub /etc/apk/keys/
    #   if: ${{ inputs.install-public-key }}