name: Linting

on:
  pull_request:
    branches: [ 'main', 'release-*' ]
  push:
    branches:
      - "main"

jobs:

  action-lint:
    name: Action lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - id: get_yamls
        run: |
          yamls=$(find . -name "*.yaml")
          echo "::set-output name=files::${yamls}"
      - uses: reviewdog/action-actionlint@v1
        with:
          actionlint_flags: ${{ steps.get_yamls.outputs.files }}