name: Testing

on:
  push:
    branches:
      - "main"

jobs:

  gen-key:
    name: gen-key test
    runs-on: ubuntu-latest

    steps:
      - id: gen_key
        uses: tuananh/actions/gen-key@main
        with:
          email: ci@tuananh.org
      - name: print pub key
        run: |
          echo ${{ steps.gen_key.outputs.pub-key }}
  
  setup-crane:
    name: setup-crane test
    runs-on: ubuntu-latest

    steps:
      - uses: tuananh/actions/setup-crane@main
        with:
          ref: main
      - name: test crane
        run: |
          crane version

  setup-tflint:
    name: setup-tflint test
    runs-on: ubuntu-latest

    steps:
      - uses: tuananh/actions/setup-tflint@main
      - name: test tflint
        run: |
          tflint --version
  setup-tfdocs:
    name: setup-tfdocs test
    runs-on: ubuntu-latest

    steps:
      - uses: tuananh/actions/setup-tfdocs@main
      - name: test tfdocs
        run: |
          terraform-docs --version

  kaniko-build:
    name: kaniko-build test
    runs-on: ubuntu-latest

    # we need this for testing kaniko-build (uploading go ghcr.io)
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v3
      - uses: tuananh/actions/kaniko-build@main
        with:
          dockerfile: ./kaniko-build/test.Dockerfile
          registry-url: ghcr.io
          registry-username: ${{ github.owner }}
          registry-password: ${{ github.token }}
          reproducible: true
          destination: ghcr.io/tuananh/kaniko-build-test:${GITHUB_SHA::7}
          # no-push: true